### ISSUE TITLE
ClassApplier should check Attributes during applyToTextNode() and isRemovable()

### ISSUE THREAD

**Issue by betson** [timdown/rangy#206]
Source: https://github.com/timdown/rangy/blob/780f783/src/js/modules/rangy-cssclassapplier.js#L681-L684

Within `createContainer()`, we ensure the new element has all of the expected properties and attributes. If `useExistingElements`, then we should maintain consistency by ensuring the existing elements already have the requested attributes.

This should be done in `applyToTextNode()` and `isRemovable()`.

**Comment by timdown** [comment]
Here is a summary of the issues, which is as much for my benefit as anything else:

`elementProperties` has existed since version 1.2 and works as follows for a class applier with class "someClass":

- All properties are added to any new element created with class "someClass"
- For an existing element to be reused when applying the class, the element's properties must match `elementProperties`. Otherwise, a new element is created.
- For an element with class "someClass" to be removed when applying a class, the element's properties must match `elementProperties`. Otherwise, "someClass" is removed from the element (so long as it has the correct tagName).

I have changed the code to do the same thing for `elementAttributes`. However, there are potential problems with this:

- Attributes set properties. Properties sometimes set properties. Therefore, if `elementProperties` has a property that matches an attribute in `elementAttributes`, things will almost certainly go wrong.  Trying to detect or work around this is tricky because the property name corresponding to an attribute is not always predictable.
- Old IE. `setAttribute()` and `getAttribute()` do not behave properly: they get/set a property rather than an attribute. This means that, for example, trying to create `<a>` elements with an `href` attribute will go wrong in old IE with a relative URL. An edge case, maybe, but it's the kind of thing I like to work around. However, the scope of working around every such case seems too great to me.

I may leave it as it is now and in the documentation suggest being very careful with using both `elementProperties` and  `elementAttributes`.
