### ISSUE TITLE
Clarify `selectNode` and `selectNodeContents` in the documentation/wiki

### ISSUE THREAD

**Issue by fresheneesz** [timdown/rangy#277]
What these actually do is incredibly unclear to me. On MDN they don't make it clear either. Does this mutate the range? Does it change the selection at all? What do they do?

**Comment by timdown** [comment]
Range methods never affect the selection. It's an unfortunate use of the word "select".

I'll update the docs to be clearer.

**Comment by timdown** [comment]
Docs updated.

**Comment by fresheneesz** [comment]
@timdown Great, that's much clearer! The only question I have is what happens when those methods are called on a range that already has some selection associated with it? Does it completely change the selection, or does it just "grow" the selection?

**Comment by fresheneesz** [comment]
Btw, I hope you don't mind a completely unrelated request here, but I was wondering if maybe you knew the answer to my question here: http://stackoverflow.com/questions/28625615/how-can-i-tell-if-a-text-input-field-dom-node-does-not-have-a-selection-with-j

**Comment by timdown** [comment]
Browsers disagree about what should happen when you change a range that belongs to a selection. Previous versions of the (unfinished) spec have said that changing a range belonging to a selection should update the selection. There has been some discussion about it on the W3C public-webapps mailing list recently:

https://github.com/w3c/selection-api/issues/40
http://lists.w3.org/Archives/Public/public-webapps/2015JanMar/0029.html

Rangy, to achieve consistency between browsers, implements it so that changing a range belonging to a selection (for instance using `setStart()`, `setEnd()` or `selectNode()`) has no effect on the selection.

See also issue #80.

**Comment by fresheneesz** [comment]
How does it affect the range itself tho? For example, lets say we have something like this:

`<div><span>some te|xt</span><span>mor|e text</span></div>`

and you select text between the two bars `|`. If you get that range, then select the second span for it. Is it now a range that defines the selection "mor"? Or does it reset the offsets to 0? Or does it still contain the original offsets that related to the div?

**Comment by timdown** [comment]
What do you mean by "select" in each case? I'm struggling to work out exactly what you're asking, sorry.

**Comment by fresheneesz** [comment]
Oh sorry, yeah let me clarify. In that example i'm saying you select text between two bars by clicking on one bar and dragging to the next so the text you'd select is "xtmore". If you get the range object `window.getSelection().getRangeAt(0)`, I'm asking what happens to the range object  when you call `selectNode` on it.

**Comment by timdown** [comment]
`selectNode()` and `selectNodeContents()` in general have no effect on the user selection. If you have an element or text node `node` then calling `range.selectNode(node)` is equivalent to `range.setStartBefore(el); range.setEndAfter(el)`
