### ISSUE TITLE
Rangy initialization fails when loaded in iframe on firefox

### ISSUE THREAD

**Issue by dosapati** [timdown/rangy#283]
Load latest rangy core and runs into a issue on firefox 
Same error as explained in issue #138.

**Comment by timdown** [comment]
Ignore that commit. I got the issue number wrong.

**Comment by timdown** [comment]
The question is what to do about it. Rangy can't initialize if it can't get hold of a selection, so I think it is correct to fail. I've improved the error handling so that it fails with a more informative message.

If you need to load Rangy in an iframe which is initially hidden and later displayed, I suggest setting `rangy.config.autoInitialize = false;` and initializing Rangy manually when you display the iframe with `rangy.init()`.

**Comment by dosapati** [comment]
Actually I wasn't loading Rangy in an iframe. Any way the suggestion might be helpful. Will try this option and update you.

Thanks once again for the help.

**Comment by timdown** [comment]
OK. Can you let me know how to replicate the error? Rangy loads without error for me in a regular page in Firefox.
