### ISSUE TITLE
Problem with Rangy.getSelection() and capitalize

### ISSUE THREAD

**Issue by mpperez3** [timdown/rangy#301]
An error occurs when use capitalize first letter with css (chrome and IE) and Rangy.getSelection().
You can see the problem on the following link:
http://jsbin.com/nelirobotu/11/edit

**Comment by timdown** [comment]
Well, this opens a can of worms. Chrome and Opera (i.e. Blink) seem generally all kinds of broken with `:first-letter` and white space preceding the first actual letter without any Rangy involvement:

http://jsbin.com/vubiredoka/1

Note that `text-transform` is not necessary: any style property seems to trigger the issue.

Also, your JSBin seems fine for me in IE 11.

Since this is a pretty catastrophic browser bug, I don't think there's anything Rangy can do.

There is a Chromium bug for this: https://code.google.com/p/chromium/issues/detail?id=406218
