### ISSUE TITLE
rangy.getSelection().toString() does not maintain new lines

### ISSUE THREAD

**Issue by tarrencev** [timdown/rangy#306]
I noticed that using the rangy selection api does not return a string that preserves new lines while the native selection api does. Is this intentional? I'm using it for a Firefox innerText polyfill

**Comment by timdown** [comment]
Yes, it's intentional. Browsers don't agree, the spec has changed at least once and at present [says nothing](https://dvcs.w3.org/hg/editing/raw-file/tip/editing.html#dom-selection-stringifier) and emulating the `innerText`-like behaviour of either Gecko or WebKit is extremely complicated, so I chose the simplest option of concatenating the result of calling `toString()` on each range in the selection, which is what an older version of the HTML5 spec said and is what Internet Explorer does.

Rangy does have an `innerText` implementation now as part of the [TextRange module](https://github.com/timdown/rangy/wiki/Text-Range-Module).

```
rangy.innerText(element);
```

**Comment by tarrencev** [comment]
Great, thanks for the response
