### ISSUE TITLE
What is this error and why is it replacing the cursor with a unicode char?

### ISSUE THREAD

**Issue by BobWalsh** [timdown/rangy#322]
I'm seeing in a contenteditable where we're using rangy to save the current selection, do some text manipulation, then restore selection this sometime error:

Uncaught HierarchyRequestError: Failed to execute 'insertBefore' on 'Node': Only one element on document allowed.

rangy is then inserting the following unicode where the caret is - so "window summer hot" becomes
<pre>
 window su%&65279;mmer hot 
</pre>

How do I prevent the error, or try/catch it?

**Comment by timdown** [comment]
The character in question is just there so that the selection marker element Rangy inserts has some content. It's a Unicode Byte Order Mark character, hackishly chosen because it renders as zero width in all of Rangy's target browsers.

I can't replicate the issue, however. Which browser are you using and what steps will reproduce the issue?

**Comment by BobWalsh** [comment]
neither can I, sorry to bother you!

**Comment by shardator** [comment]
Hi, I can reproduce the error. My code is an input handler in a contenteditable, doing this:

``` js
        var textval = $(this).html().replace(/\s/g, ' ').trim();

        var savedSel = rangy.saveSelection();
        $(this).html(textval);
        try { rangy.restoreSelection(savedSel); } catch (Z) {}
```

I thought this is just as simple, but it looks like it's not.  I get:

```
HierarchyRequestError: Node cannot be inserted at the specified point in the hierarchy
```

in rangy-core.js.
