### ISSUE TITLE
Keep Selection with applyToRange and undoToRange

### ISSUE THREAD

**Issue by Solaner** [timdown/rangy#332]
In my intended use of Rangy I would like to **apply** a highlighter class to a range, while the current selection should remain. Also when I **undo** the class to the range, the current selection should not be modified.
To see what I'm trying to do and the resulting effects in my [**first JSBin**](http://jsbin.com/zazegu/2/edit?html,css,js,console,output) you can do the following:
1. Click a number of times the button **`Apply Next`**. This will highlight some words.
2. Click a number of times the button **`Undo Next`**. This will remove the previous applied highlights.
3. Press "Run with JS" to start the next test.
4. Select some text in the first phrase of the text.
5. Repeat point 1 and 2. The selection will (at least partly) disappear.
In my [**second JSBin**](http://jsbin.com/zazegu/4/edit?html,css,js,console,output) you see one of my tried workarounds.
Before the command `applyToRange` or `undoToRange` I save the selection (`saveSelection`) and want to restore it afterwards (`restoreSelection`). However instead of the selection to remain, error messages appear in the Console.
I have tried similar aproaches in local code. I have tried also `serializeSelection` and `deserializeSelection` without success.
Is there a way to keep the selection while applying and undoing classes?

**Comment by timdown** [comment]
The problem is that saving and restoring the selection using the save/restore module inserts and removes elements, which is messing up the your ranges. I'd suggest using one of the character offset-based methods which works well when the elements may change but the text itself doesn't. Every Rangy range has `getBookmark()` and `moveToBookmark()` which is relatively efficient but doesn't handle line breaks well. Here's an example using these:

http://jsbin.com/sututiyati/2/edit?js,console,output

A more heavyweight option that does much the same thing and also handles line breaks and many other issues but is significantly slower is the `toCharacterRange()` and `selectCharacters()` methods of Rangy range, provided by the TextRange module.

**Comment by Solaner** [comment]
I have adapted your solution to my local code (which is quite different) and still had issues due to DOM changes.
Based on your suggestions, after a lot of trials, I have developed the following two functions.
```javascript
function GetSelectionBookmark() {
	var sel = rangy.getSelection();
	if (!sel)
		return null;
	var rangyRange = sel.getAllRanges()[0];
	if (!rangyRange)
		return null;
	var bookmark = rangyRange.getBookmark(document.body);
	bookmark.direction = sel.isBackward() ? "backward" : "forward";
	return bookmark;
}
```
and
```javascript
function SetSelectionBookmark(bookmark) {
	if (bookmark == null)
		return;
	var rangyRange = rangy.createRange();
	rangyRange.moveToBookmark(bookmark);
	var sel = rangy.getSelection();
	sel.removeAllRanges();
	sel.addRange(rangyRange, bookmark.direction);
}
```
They work well in my current test pages with Firefox.
Here's a JSBin containing the above functions:
http://jsbin.com/gojula/2/edit?js,console,output
I have learned a lot. Thank you very much!
