### ISSUE TITLE
findText() does not respect the withinRange flag and searches the whole document

### ISSUE THREAD

**Issue by yattias** [timdown/rangy#346]
The loop below will not stop until the end of the document is reached.

```
        var searchScopeRange   = rangy.createRange();

        searchScopeRange.selectNodeContents(searchScopeNode); // Just a paragraph in this case.

        var options = {
            caseSensitive:  true,
            wholeWordsOnly: false,
            withinRange:    searchScopeRange
        };

        while (searchScopeRange.findText(searchTerm, options)) {
            // Move the range pointer forward
            searchScopeRange.collapse(false);
        }
```

You can use the parent element to confirm that the containing parent changes

```
    function getRangeParentElement(range) {
        var parentEl = range.commonAncestorContainer;

        if (parentEl && parentEl.nodeType != Node.ELEMENT_NODE) {
            parentEl = parentEl.parentNode;
        }

        return parentEl;
    },
```

**Comment by timdown** [comment]
The problem is that you're changing the search scope range after each match. You need to leave that range alone and use another range that moves with each match.

Create a range that starts at the point at which you want to start the search;

{{{
var range = rangy.createRange();
range.selectNodeContents(searchScopeNode);
}}}

Move this range after dealing with each match:

{{{
while (range.findText(searchTerm, options)) {
    // Do stuff here
    // Move the range pointer forward
    range.collapse(false);
}
}}}

I admit it's slightly confusing; perhaps I shouldn't have copied IE's TextRange API quite so slavishly in this case.
